// automatically generated by the FlatBuffers compiler, do not modify

package in.dragonbra.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlightsFb extends Table {
  public static FlightsFb getRootAsFlightsFb(ByteBuffer _bb) { return getRootAsFlightsFb(_bb, new FlightsFb()); }
  public static FlightsFb getRootAsFlightsFb(ByteBuffer _bb, FlightsFb obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FlightsFb __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlightFb flights(int j) { return flights(new FlightFb(), j); }
  public FlightFb flights(FlightFb obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int flightsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createFlightsFb(FlatBufferBuilder builder,
      int flightsOffset) {
    builder.startObject(1);
    FlightsFb.addFlights(builder, flightsOffset);
    return FlightsFb.endFlightsFb(builder);
  }

  public static void startFlightsFb(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addFlights(FlatBufferBuilder builder, int flightsOffset) { builder.addOffset(0, flightsOffset, 0); }
  public static int createFlightsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFlightsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFlightsFb(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFlightsFbBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

